import { Evolution } from './types';

// ===== 🌰 ACORN TREE (Trees & Woods) =====

export const ACORN_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'acorn_seed',
    name: 'Acorn',
    emoji: '🌰',
    seedId: 'acorn',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'acorn_sapling',
    rarity: 'common',
  },
  
  // Tier 1 - Sapling
  {
    id: 'acorn_sapling',
    name: 'Sapling',
    emoji: '🪴',
    seedId: 'acorn',
    tier: 1,
    growthTime: 45000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'acorn_seed',
    defaultEvolution: 'acorn_young_tree',
    specialEvolutions: [
      {
        evolutionId: 'acorn_bamboo',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Quick water bursts help bamboo...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: Trees
  {
    id: 'acorn_young_tree',
    name: 'Young Tree',
    emoji: '🌲',
    seedId: 'acorn',
    tier: 2,
    growthTime: 90000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'acorn_sapling',
    defaultEvolution: 'acorn_pine',
    specialEvolutions: [
      {
        evolutionId: 'acorn_fruit_tree',
        trigger: { type: 'visitor_touch', visitor: 'bee' },
        hint: 'Bees help trees bear fruit...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Bamboo/Reed
  {
    id: 'acorn_bamboo',
    name: 'Bamboo Shoot',
    emoji: '🎋',
    seedId: 'acorn',
    tier: 2,
    growthTime: 60000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'acorn_sapling',
    defaultEvolution: 'acorn_bamboo_grove',
    specialEvolutions: [
      {
        evolutionId: 'acorn_panda_bamboo',
        trigger: { type: 'visitor_touch', visitor: 'rabbit' },
        hint: 'Cute creatures love bamboo...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Trees
  {
    id: 'acorn_pine',
    name: 'Pine',
    emoji: '🌲',
    seedId: 'acorn',
    tier: 3,
    growthTime: 120000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'acorn_young_tree',
    defaultEvolution: 'acorn_oak',
    specialEvolutions: [
      {
        evolutionId: 'acorn_festive',
        trigger: { type: 'month', month: 12 },
        hint: 'December magic...',
      },
      {
        evolutionId: 'acorn_palm',
        trigger: { type: 'neighbor_count', min: 2 },
        hint: 'Tropical vibes with friends...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'acorn_fruit_tree',
    name: 'Fruit Tree',
    emoji: '🍎',
    seedId: 'acorn',
    tier: 3,
    growthTime: 100000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'acorn_young_tree',
    defaultEvolution: 'acorn_apple',
    specialEvolutions: [
      {
        evolutionId: 'acorn_citrus',
        trigger: { type: 'golden' },
        hint: 'Golden fruit trees...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Bamboo
  {
    id: 'acorn_bamboo_grove',
    name: 'Bamboo Grove',
    emoji: '🎍',
    seedId: 'acorn',
    tier: 3,
    growthTime: 80000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'acorn_bamboo',
    defaultEvolution: 'acorn_imperial_bamboo',
    rarity: 'uncommon',
  },
  
  {
    id: 'acorn_panda_bamboo',
    name: 'Panda Bamboo',
    emoji: '🐼',
    seedId: 'acorn',
    tier: 3,
    growthTime: 90000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'acorn_bamboo',
    defaultEvolution: 'acorn_panda_grove',
    rarity: 'rare',
  },
  
  // Tier 4 - Trees
  {
    id: 'acorn_oak',
    name: 'Oak',
    emoji: '🌳',
    seedId: 'acorn',
    tier: 4,
    growthTime: 180000,
    visualScale: 1.8,
    pointValue: 0,
    evolvesFrom: 'acorn_pine',
    defaultEvolution: 'acorn_grand_oak',
    specialEvolutions: [
      {
        evolutionId: 'acorn_wise_oak',
        trigger: { type: 'age', hours: 2 },
        hint: 'Wisdom comes with age...',
      },
      {
        evolutionId: 'acorn_maple',
        trigger: { type: 'season', season: 'fall' },
        hint: 'Autumn colors...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'acorn_festive',
    name: 'Festive Tree',
    emoji: '🎄',
    seedId: 'acorn',
    tier: 4,
    growthTime: 120000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'acorn_pine',
    defaultEvolution: 'acorn_star_tree',
    rarity: 'rare',
  },
  
  {
    id: 'acorn_palm',
    name: 'Palm',
    emoji: '🌴',
    seedId: 'acorn',
    tier: 4,
    growthTime: 150000,
    visualScale: 1.7,
    pointValue: 0,
    evolvesFrom: 'acorn_pine',
    defaultEvolution: 'acorn_paradise_palm',
    specialEvolutions: [
      {
        evolutionId: 'acorn_coconut',
        trigger: { type: 'harvest_spot', count: 3 },
        hint: 'Bountiful spots bear more...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 4 - Fruit
  {
    id: 'acorn_apple',
    name: 'Apple Tree',
    emoji: '🍎',
    seedId: 'acorn',
    tier: 4,
    growthTime: 150000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'acorn_fruit_tree',
    defaultEvolution: 'acorn_golden_apple',
    rarity: 'uncommon',
  },
  
  {
    id: 'acorn_citrus',
    name: 'Citrus Grove',
    emoji: '🍊',
    seedId: 'acorn',
    tier: 4,
    growthTime: 140000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'acorn_fruit_tree',
    defaultEvolution: 'acorn_orange_tree',
    rarity: 'rare',
  },
  
  // Tier 4 - Bamboo
  {
    id: 'acorn_imperial_bamboo',
    name: 'Imperial Bamboo',
    emoji: '🏯',
    seedId: 'acorn',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'acorn_bamboo_grove',
    defaultEvolution: 'acorn_zen_bamboo',
    rarity: 'rare',
  },
  
  {
    id: 'acorn_panda_grove',
    name: 'Panda Grove',
    emoji: '🐼',
    seedId: 'acorn',
    tier: 4,
    growthTime: 120000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'acorn_panda_bamboo',
    defaultEvolution: 'acorn_panda_paradise',
    rarity: 'epic',
  },
  
  // Tier 5 - MAX Trees
  {
    id: 'acorn_grand_oak',
    name: 'Grand Oak',
    emoji: '🌳',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 8,
    evolvesFrom: 'acorn_oak',
    defaultEvolution: null,
    rarity: 'common',
    description: 'A mighty oak, standing tall.',
  },
  
  {
    id: 'acorn_wise_oak',
    name: 'Wise Oak',
    emoji: '🦉',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 12,
    evolvesFrom: 'acorn_oak',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'acorn_world_tree',
        trigger: { type: 'all_neighbors_max' },
        hint: 'Surrounded by greatness...',
      },
    ],
    rarity: 'epic',
    description: 'Ancient wisdom in every ring.',
  },
  
  {
    id: 'acorn_maple',
    name: 'Autumn Maple',
    emoji: '🍁',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 1.9,
    pointValue: 9,
    evolvesFrom: 'acorn_oak',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'acorn_syrup_maple',
        trigger: { type: 'visitor_touch', visitor: 'bee' },
        hint: 'Sweet visitors...',
      },
    ],
    rarity: 'rare',
    description: 'Brilliant fall colors.',
  },
  
  {
    id: 'acorn_star_tree',
    name: 'Star Tree',
    emoji: '⭐',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 15,
    evolvesFrom: 'acorn_festive',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Topped with starlight.',
  },
  
  {
    id: 'acorn_paradise_palm',
    name: 'Paradise Palm',
    emoji: '🏝️',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 10,
    evolvesFrom: 'acorn_palm',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Island dreams.',
  },
  
  {
    id: 'acorn_coconut',
    name: 'Coconut King',
    emoji: '🥥',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 11,
    evolvesFrom: 'acorn_palm',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Abundant tropical bounty.',
  },
  
  // Tier 5 - MAX Fruit
  {
    id: 'acorn_golden_apple',
    name: 'Golden Apple',
    emoji: '🍏',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 10,
    evolvesFrom: 'acorn_apple',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'acorn_orchard_queen',
        trigger: { type: 'neighbor_same', min: 3 },
        hint: 'An orchard needs company...',
      },
    ],
    rarity: 'rare',
    description: 'Prized golden fruit.',
  },
  
  {
    id: 'acorn_orange_tree',
    name: 'Orange Tree',
    emoji: '🍊',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 9,
    evolvesFrom: 'acorn_citrus',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Sweet citrus abundance.',
  },
  
  // Tier 5 - MAX Bamboo
  {
    id: 'acorn_zen_bamboo',
    name: 'Zen Bamboo',
    emoji: '🎋',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 11,
    evolvesFrom: 'acorn_imperial_bamboo',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Perfect tranquility.',
  },
  
  {
    id: 'acorn_panda_paradise',
    name: 'Panda Paradise',
    emoji: '🐼',
    seedId: 'acorn',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 15,
    evolvesFrom: 'acorn_panda_grove',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'A panda\'s dream home.',
  },
  
  // Tier 6 - LEGENDARY
  {
    id: 'acorn_world_tree',
    name: 'World Tree',
    emoji: '🌍',
    seedId: 'acorn',
    tier: 6,
    growthTime: 0,
    visualScale: 2.5,
    pointValue: 50,
    evolvesFrom: 'acorn_wise_oak',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Yggdrasil, the tree of life.',
  },
  
  {
    id: 'acorn_syrup_maple',
    name: 'Syrup Maple',
    emoji: '🍯',
    seedId: 'acorn',
    tier: 6,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 20,
    evolvesFrom: 'acorn_maple',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'The sweetest tree in existence.',
  },
  
  {
    id: 'acorn_orchard_queen',
    name: 'Orchard Queen',
    emoji: '🧺',
    seedId: 'acorn',
    tier: 6,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 25,
    evolvesFrom: 'acorn_golden_apple',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Ruler of all fruit trees.',
  },
];
