import { Evolution } from './types';

// ===== 🫘 BEAN TREE (Climbers & Vines) =====

export const BEAN_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'bean_seed',
    name: 'Bean',
    emoji: '🫘',
    seedId: 'bean',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'bean_sprout',
    rarity: 'common',
  },
  
  // Tier 1
  {
    id: 'bean_sprout',
    name: 'Bean Sprout',
    emoji: '🌱',
    seedId: 'bean',
    tier: 1,
    growthTime: 25000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'bean_seed',
    defaultEvolution: 'bean_vine',
    specialEvolutions: [
      {
        evolutionId: 'bean_pea',
        trigger: { type: 'farmer_boosted', count: 5 },
        hint: 'Farmer\'s favorites...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: Vines
  {
    id: 'bean_vine',
    name: 'Vine',
    emoji: '🍇',
    seedId: 'bean',
    tier: 2,
    growthTime: 40000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'bean_sprout',
    defaultEvolution: 'bean_grape',
    specialEvolutions: [
      {
        evolutionId: 'bean_gourd',
        trigger: { type: 'neighbor_count', min: 2 },
        hint: 'Vines like to spread...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Legumes
  {
    id: 'bean_pea',
    name: 'Pea Pod',
    emoji: '🫛',
    seedId: 'bean',
    tier: 2,
    growthTime: 35000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'bean_sprout',
    defaultEvolution: 'bean_sweet_pea',
    specialEvolutions: [
      {
        evolutionId: 'bean_magic',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Magic requires speed...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Vines
  {
    id: 'bean_grape',
    name: 'Grape Vine',
    emoji: '🍇',
    seedId: 'bean',
    tier: 3,
    growthTime: 50000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bean_vine',
    defaultEvolution: 'bean_wine_grape',
    specialEvolutions: [
      {
        evolutionId: 'bean_kiwi',
        trigger: { type: 'night_water', count: 2 },
        hint: 'Exotic fruits prefer shade...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'bean_gourd',
    name: 'Gourd',
    emoji: '🥒',
    seedId: 'bean',
    tier: 3,
    growthTime: 45000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bean_vine',
    defaultEvolution: 'bean_melon',
    specialEvolutions: [
      {
        evolutionId: 'bean_pumpkin',
        trigger: { type: 'month', month: 10 },
        hint: 'October magic...',
      },
      {
        evolutionId: 'bean_pepper',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Fast watering brings the heat...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Legumes
  {
    id: 'bean_sweet_pea',
    name: 'Sweet Pea',
    emoji: '🫛',
    seedId: 'bean',
    tier: 3,
    growthTime: 45000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'bean_pea',
    defaultEvolution: 'bean_garden_pea',
    rarity: 'uncommon',
  },
  
  {
    id: 'bean_magic',
    name: 'Magic Bean',
    emoji: '🪄',
    seedId: 'bean',
    tier: 3,
    growthTime: 55000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bean_pea',
    defaultEvolution: 'bean_cloud',
    rarity: 'rare',
  },
  
  // Tier 4 - Vines
  {
    id: 'bean_wine_grape',
    name: 'Wine Grape',
    emoji: '🍷',
    seedId: 'bean',
    tier: 4,
    growthTime: 70000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bean_grape',
    defaultEvolution: 'bean_vineyard',
    specialEvolutions: [
      {
        evolutionId: 'bean_royal_vineyard',
        trigger: { type: 'age', hours: 1 },
        hint: 'Good wine takes time...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'bean_kiwi',
    name: 'Kiwi',
    emoji: '🥝',
    seedId: 'bean',
    tier: 4,
    growthTime: 60000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bean_grape',
    defaultEvolution: 'bean_star_fruit',
    rarity: 'rare',
  },
  
  {
    id: 'bean_melon',
    name: 'Melon',
    emoji: '🍈',
    seedId: 'bean',
    tier: 4,
    growthTime: 65000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bean_gourd',
    defaultEvolution: 'bean_watermelon',
    specialEvolutions: [
      {
        evolutionId: 'bean_moon_melon',
        trigger: { type: 'night_water', count: 5 },
        hint: 'Moonlit melons...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'bean_pumpkin',
    name: 'Pumpkin',
    emoji: '🎃',
    seedId: 'bean',
    tier: 4,
    growthTime: 80000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'bean_gourd',
    defaultEvolution: 'bean_giant_pumpkin',
    specialEvolutions: [
      {
        evolutionId: 'bean_ghost_pumpkin',
        trigger: { type: 'night_water', count: 3 },
        hint: 'Spooky night waters...',
      },
    ],
    rarity: 'rare',
  },
  
  {
    id: 'bean_pepper',
    name: 'Pepper',
    emoji: '🌶️',
    seedId: 'bean',
    tier: 4,
    growthTime: 60000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bean_gourd',
    defaultEvolution: 'bean_chili',
    specialEvolutions: [
      {
        evolutionId: 'bean_rainbow_pepper',
        trigger: { type: 'neighbor_diverse', min: 4 },
        hint: 'Diversity brings color...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 4 - Legumes
  {
    id: 'bean_garden_pea',
    name: 'Garden Pea',
    emoji: '💚',
    seedId: 'bean',
    tier: 4,
    growthTime: 55000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bean_sweet_pea',
    defaultEvolution: 'bean_pea_pod',
    rarity: 'uncommon',
  },
  
  {
    id: 'bean_cloud',
    name: 'Cloud Bean',
    emoji: '☁️',
    seedId: 'bean',
    tier: 4,
    growthTime: 75000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bean_magic',
    defaultEvolution: 'bean_sky_bean',
    specialEvolutions: [
      {
        evolutionId: 'bean_golden_goose',
        trigger: { type: 'golden' },
        hint: 'Golden clouds...',
      },
    ],
    rarity: 'epic',
  },
  
  // Tier 5 - MAX
  {
    id: 'bean_vineyard',
    name: 'Vineyard',
    emoji: '🍇',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 8,
    evolvesFrom: 'bean_wine_grape',
    defaultEvolution: null,
    rarity: 'uncommon',
    description: 'A bountiful grape harvest.',
  },
  
  {
    id: 'bean_royal_vineyard',
    name: 'Royal Vineyard',
    emoji: '🏰',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.9,
    pointValue: 12,
    evolvesFrom: 'bean_wine_grape',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Fit for royalty.',
  },
  
  {
    id: 'bean_star_fruit',
    name: 'Star Fruit',
    emoji: '⭐',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 10,
    evolvesFrom: 'bean_kiwi',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Exotic and stellar.',
  },
  
  {
    id: 'bean_watermelon',
    name: 'Watermelon',
    emoji: '🍉',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 8,
    evolvesFrom: 'bean_melon',
    defaultEvolution: null,
    rarity: 'common',
    description: 'Summer sweetness.',
  },
  
  {
    id: 'bean_moon_melon',
    name: 'Moon Melon',
    emoji: '🌙',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 12,
    evolvesFrom: 'bean_melon',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'bean_crystal_melon',
        trigger: { type: 'golden' },
        hint: 'Golden moonlight...',
      },
    ],
    rarity: 'epic',
    description: 'Glows under moonlight.',
  },
  
  {
    id: 'bean_giant_pumpkin',
    name: 'Giant Pumpkin',
    emoji: '🏆',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 10,
    evolvesFrom: 'bean_pumpkin',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Prize-winning size.',
  },
  
  {
    id: 'bean_ghost_pumpkin',
    name: 'Ghost Pumpkin',
    emoji: '🎃',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 15,
    evolvesFrom: 'bean_pumpkin',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Spooky but friendly.',
  },
  
  {
    id: 'bean_chili',
    name: 'Fire Chili',
    emoji: '🔥',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 9,
    evolvesFrom: 'bean_pepper',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'bean_dragon',
        trigger: { type: 'neighbor_evolution', evolutionId: 'bean_chili' },
        hint: 'Fire breeds fire...',
      },
    ],
    rarity: 'rare',
    description: 'Intensely hot!',
  },
  
  {
    id: 'bean_rainbow_pepper',
    name: 'Rainbow Pepper',
    emoji: '🌈',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 11,
    evolvesFrom: 'bean_pepper',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Every color imaginable.',
  },
  
  {
    id: 'bean_pea_pod',
    name: 'Perfect Pea Pod',
    emoji: '🫛',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.4,
    pointValue: 6,
    evolvesFrom: 'bean_garden_pea',
    defaultEvolution: null,
    rarity: 'common',
    description: 'Perfectly plump peas.',
  },
  
  {
    id: 'bean_sky_bean',
    name: 'Sky Bean',
    emoji: '🌤️',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 15,
    evolvesFrom: 'bean_cloud',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Reaches for the heavens.',
  },
  
  {
    id: 'bean_golden_goose',
    name: 'Golden Goose Bean',
    emoji: '🥚',
    seedId: 'bean',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 20,
    evolvesFrom: 'bean_cloud',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Lays golden eggs... metaphorically.',
  },
  
  // Tier 6 - LEGENDARY
  {
    id: 'bean_crystal_melon',
    name: 'Crystal Melon',
    emoji: '�',
    seedId: 'bean',
    tier: 6,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 25,
    evolvesFrom: 'bean_moon_melon',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Pure crystallized sweetness.',
  },
  
  {
    id: 'bean_dragon',
    name: 'Dragon Pepper',
    emoji: '🐉',
    seedId: 'bean',
    tier: 6,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 30,
    evolvesFrom: 'bean_chili',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Breathes actual fire.',
  },
];
