import { Evolution } from './types';

// ===== 🧅 BULB TREE (Underground & Root) =====

export const BULB_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'bulb_seed',
    name: 'Bulb',
    emoji: '🧅',
    seedId: 'bulb',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'bulb_sprout',
    rarity: 'common',
  },
  
  // Tier 1
  {
    id: 'bulb_sprout',
    name: 'Bulb Sprout',
    emoji: '🌱',
    seedId: 'bulb',
    tier: 1,
    growthTime: 35000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'bulb_seed',
    defaultEvolution: 'bulb_onion',
    specialEvolutions: [
      {
        evolutionId: 'bulb_root',
        trigger: { type: 'night_water', count: 1 },
        hint: 'Roots grow in darkness...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: Alliums
  {
    id: 'bulb_onion',
    name: 'Onion',
    emoji: '🧅',
    seedId: 'bulb',
    tier: 2,
    growthTime: 50000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'bulb_sprout',
    defaultEvolution: 'bulb_golden_onion',
    specialEvolutions: [
      {
        evolutionId: 'bulb_garlic',
        trigger: { type: 'night_water', count: 2 },
        hint: 'Garlic loves the dark...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Roots
  {
    id: 'bulb_root',
    name: 'Root',
    emoji: '🥕',
    seedId: 'bulb',
    tier: 2,
    growthTime: 45000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'bulb_sprout',
    defaultEvolution: 'bulb_carrot',
    specialEvolutions: [
      {
        evolutionId: 'bulb_potato',
        trigger: { type: 'neighbor_same', min: 2 },
        hint: 'Potatoes grow in groups...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 2 - Branch C: Flowering Bulbs
  {
    id: 'bulb_bloom',
    name: 'Bulb Bloom',
    emoji: '🌺',
    seedId: 'bulb',
    tier: 2,
    growthTime: 55000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bulb_sprout',
    defaultEvolution: 'bulb_daffodil',
    specialEvolutions: [
      {
        evolutionId: 'bulb_lotus',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Water lilies need lots of water...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Alliums
  {
    id: 'bulb_golden_onion',
    name: 'Golden Onion',
    emoji: '🧅',
    seedId: 'bulb',
    tier: 3,
    growthTime: 60000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bulb_onion',
    defaultEvolution: 'bulb_onion_king',
    specialEvolutions: [
      {
        evolutionId: 'bulb_onion_king',
        trigger: { type: 'neighbor_same', min: 3 },
        hint: 'Surround with onion allies...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'bulb_garlic',
    name: 'Garlic',
    emoji: '🧄',
    seedId: 'bulb',
    tier: 3,
    growthTime: 55000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'bulb_onion',
    defaultEvolution: 'bulb_garlic_braid',
    specialEvolutions: [
      {
        evolutionId: 'bulb_vampire_garlic',
        trigger: { type: 'night_water', count: 5 },
        hint: 'Only the darkest nights...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Roots
  {
    id: 'bulb_carrot',
    name: 'Carrot',
    emoji: '🥕',
    seedId: 'bulb',
    tier: 3,
    growthTime: 50000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'bulb_root',
    defaultEvolution: 'bulb_golden_carrot',
    specialEvolutions: [
      {
        evolutionId: 'bulb_bunny_carrot',
        trigger: { type: 'visitor_touch', visitor: 'rabbit' },
        hint: 'Bunnies love carrots...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'bulb_potato',
    name: 'Potato',
    emoji: '🥔',
    seedId: 'bulb',
    tier: 3,
    growthTime: 55000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'bulb_root',
    defaultEvolution: 'bulb_golden_potato',
    specialEvolutions: [
      {
        evolutionId: 'bulb_potato_castle',
        trigger: { type: 'neighbor_same', min: 4 },
        hint: 'Build a potato empire...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Flowers
  {
    id: 'bulb_daffodil',
    name: 'Daffodil',
    emoji: '💐',
    seedId: 'bulb',
    tier: 3,
    growthTime: 60000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bulb_bloom',
    defaultEvolution: 'bulb_star_daffodil',
    specialEvolutions: [
      {
        evolutionId: 'bulb_hibiscus',
        trigger: { type: 'visitor_touch' },
        hint: 'Visitors bring color...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'bulb_lotus',
    name: 'Lotus',
    emoji: '🪷',
    seedId: 'bulb',
    tier: 3,
    growthTime: 70000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bulb_bloom',
    defaultEvolution: 'bulb_sacred_lotus',
    specialEvolutions: [
      {
        evolutionId: 'bulb_koi_pond',
        trigger: { type: 'neighbor_evolution', evolutionId: 'bulb_lotus' },
        hint: 'Lotuses attract koi...',
      },
    ],
    rarity: 'rare',
  },
  
  // Tier 4 - Alliums
  {
    id: 'bulb_onion_king',
    name: 'Onion King',
    emoji: '🤴',
    seedId: 'bulb',
    tier: 4,
    growthTime: 80000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'bulb_golden_onion',
    defaultEvolution: 'bulb_onion_emperor',
    rarity: 'rare',
  },
  
  {
    id: 'bulb_garlic_braid',
    name: 'Garlic Braid',
    emoji: '🧄',
    seedId: 'bulb',
    tier: 4,
    growthTime: 70000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bulb_garlic',
    defaultEvolution: 'bulb_garlic_fortress',
    rarity: 'uncommon',
  },
  
  {
    id: 'bulb_vampire_garlic',
    name: 'Vampire Garlic',
    emoji: '🧛',
    seedId: 'bulb',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bulb_garlic',
    defaultEvolution: 'bulb_death_bulb',
    rarity: 'epic',
  },
  
  // Tier 4 - Roots
  {
    id: 'bulb_golden_carrot',
    name: 'Golden Carrot',
    emoji: '🥕',
    seedId: 'bulb',
    tier: 4,
    growthTime: 65000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'bulb_carrot',
    defaultEvolution: 'bulb_prize_carrot',
    rarity: 'rare',
  },
  
  {
    id: 'bulb_bunny_carrot',
    name: 'Bunny Carrot',
    emoji: '🐰',
    seedId: 'bulb',
    tier: 4,
    growthTime: 70000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bulb_carrot',
    defaultEvolution: 'bulb_carrot_kingdom',
    rarity: 'epic',
  },
  
  {
    id: 'bulb_golden_potato',
    name: 'Golden Potato',
    emoji: '🥇',
    seedId: 'bulb',
    tier: 4,
    growthTime: 75000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bulb_potato',
    defaultEvolution: 'bulb_potato_crown',
    rarity: 'rare',
  },
  
  {
    id: 'bulb_potato_castle',
    name: 'Potato Castle',
    emoji: '🏰',
    seedId: 'bulb',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.8,
    pointValue: 0,
    evolvesFrom: 'bulb_potato',
    defaultEvolution: 'bulb_root_empire',
    rarity: 'epic',
  },
  
  // Tier 4 - Flowers
  {
    id: 'bulb_star_daffodil',
    name: 'Star Daffodil',
    emoji: '⭐',
    seedId: 'bulb',
    tier: 4,
    growthTime: 80000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'bulb_daffodil',
    defaultEvolution: 'bulb_celestial_bloom',
    rarity: 'rare',
  },
  
  {
    id: 'bulb_hibiscus',
    name: 'Hibiscus',
    emoji: '🌺',
    seedId: 'bulb',
    tier: 4,
    growthTime: 75000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'bulb_daffodil',
    defaultEvolution: 'bulb_tropical_bloom',
    specialEvolutions: [
      {
        evolutionId: 'bulb_flamingo',
        trigger: { type: 'neighbor_count', min: 3 },
        hint: 'Pink attracts pink...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'bulb_sacred_lotus',
    name: 'Sacred Lotus',
    emoji: '🕉️',
    seedId: 'bulb',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'bulb_lotus',
    defaultEvolution: 'bulb_enlightened_lotus',
    rarity: 'epic',
  },
  
  {
    id: 'bulb_koi_pond',
    name: 'Koi Pond',
    emoji: '🐟',
    seedId: 'bulb',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.7,
    pointValue: 0,
    evolvesFrom: 'bulb_lotus',
    defaultEvolution: 'bulb_dragon_koi',
    rarity: 'epic',
  },
  
  // Tier 5 - MAX
  {
    id: 'bulb_onion_emperor',
    name: 'Onion Emperor',
    emoji: '🏆',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 12,
    evolvesFrom: 'bulb_onion_king',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Supreme ruler of alliums.',
  },
  
  {
    id: 'bulb_garlic_fortress',
    name: 'Garlic Fortress',
    emoji: '🏯',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 10,
    evolvesFrom: 'bulb_garlic_braid',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Impenetrable garlic defense.',
  },
  
  {
    id: 'bulb_death_bulb',
    name: 'Death Bulb',
    emoji: '💀',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 18,
    evolvesFrom: 'bulb_vampire_garlic',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Not actually deadly, just dramatic.',
  },
  
  {
    id: 'bulb_prize_carrot',
    name: 'Prize Carrot',
    emoji: '🏆',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 9,
    evolvesFrom: 'bulb_golden_carrot',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Blue ribbon worthy.',
  },
  
  {
    id: 'bulb_carrot_kingdom',
    name: 'Carrot Kingdom',
    emoji: '🐰',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.9,
    pointValue: 15,
    evolvesFrom: 'bulb_bunny_carrot',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Where bunnies reign supreme.',
  },
  
  {
    id: 'bulb_potato_crown',
    name: 'Potato Crown',
    emoji: '🫅',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 11,
    evolvesFrom: 'bulb_golden_potato',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'The humblest of royalty.',
  },
  
  {
    id: 'bulb_root_empire',
    name: 'Root Empire',
    emoji: '🏰',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 22,
    evolvesFrom: 'bulb_potato_castle',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'An underground civilization.',
  },
  
  {
    id: 'bulb_celestial_bloom',
    name: 'Celestial Bloom',
    emoji: '🌟',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 14,
    evolvesFrom: 'bulb_star_daffodil',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Touched by starlight.',
  },
  
  {
    id: 'bulb_tropical_bloom',
    name: 'Tropical Bloom',
    emoji: '🌺',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 9,
    evolvesFrom: 'bulb_hibiscus',
    defaultEvolution: null,
    rarity: 'uncommon',
    description: 'Island paradise.',
  },
  
  {
    id: 'bulb_flamingo',
    name: 'Flamingo Flower',
    emoji: '🦩',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 12,
    evolvesFrom: 'bulb_hibiscus',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Impossibly elegant.',
  },
  
  {
    id: 'bulb_enlightened_lotus',
    name: 'Enlightened Lotus',
    emoji: '🕉️',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 20,
    evolvesFrom: 'bulb_sacred_lotus',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Pure spiritual energy.',
  },
  
  {
    id: 'bulb_dragon_koi',
    name: 'Dragon Koi',
    emoji: '🐉',
    seedId: 'bulb',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 22,
    evolvesFrom: 'bulb_koi_pond',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'The koi that became a dragon.',
  },
];
