import { Evolution } from './types';

// ===== 🌵 CACTUS TREE (Desert & Succulents) =====

export const CACTUS_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'cactus_seed',
    name: 'Cactus Pip',
    emoji: '🌵',
    seedId: 'cactus',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'cactus_sprout',
    rarity: 'common',
  },
  
  // Tier 1
  {
    id: 'cactus_sprout',
    name: 'Cactus Sprout',
    emoji: '🌱',
    seedId: 'cactus',
    tier: 1,
    growthTime: 50000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'cactus_seed',
    defaultEvolution: 'cactus_small',
    specialEvolutions: [
      {
        evolutionId: 'cactus_succulent',
        trigger: { type: 'farmer_boosted', count: 5 },
        hint: 'Tender loving care...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: True Cacti
  {
    id: 'cactus_small',
    name: 'Small Cactus',
    emoji: '🌵',
    seedId: 'cactus',
    tier: 2,
    growthTime: 70000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'cactus_sprout',
    defaultEvolution: 'cactus_barrel',
    specialEvolutions: [
      {
        evolutionId: 'cactus_tall',
        trigger: { type: 'age', hours: 1 },
        hint: 'Patience makes them tall...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Succulents
  {
    id: 'cactus_succulent',
    name: 'Succulent',
    emoji: '🌿',
    seedId: 'cactus',
    tier: 2,
    growthTime: 60000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'cactus_sprout',
    defaultEvolution: 'cactus_jade',
    specialEvolutions: [
      {
        evolutionId: 'cactus_rosette',
        trigger: { type: 'visitor_touch', visitor: 'butterfly' },
        hint: 'Beauty attracts beauty...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Cacti
  {
    id: 'cactus_barrel',
    name: 'Barrel Cactus',
    emoji: '�',
    seedId: 'cactus',
    tier: 3,
    growthTime: 90000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'cactus_small',
    defaultEvolution: 'cactus_water_store',
    specialEvolutions: [
      {
        evolutionId: 'cactus_ancient_barrel',
        trigger: { type: 'age', hours: 3 },
        hint: 'Ancient wisdom...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'cactus_tall',
    name: 'Tall Cactus',
    emoji: '🌵',
    seedId: 'cactus',
    tier: 3,
    growthTime: 100000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'cactus_small',
    defaultEvolution: 'cactus_saguaro',
    specialEvolutions: [
      {
        evolutionId: 'cactus_organ_pipe',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Rhythm of the desert...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Succulents
  {
    id: 'cactus_jade',
    name: 'Jade Plant',
    emoji: '🌲',
    seedId: 'cactus',
    tier: 3,
    growthTime: 80000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'cactus_succulent',
    defaultEvolution: 'cactus_gem_plant',
    specialEvolutions: [
      {
        evolutionId: 'cactus_money_tree',
        trigger: { type: 'golden' },
        hint: 'Golden fortune...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'cactus_rosette',
    name: 'Rosette',
    emoji: '�',
    seedId: 'cactus',
    tier: 3,
    growthTime: 75000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'cactus_succulent',
    defaultEvolution: 'cactus_echeveria',
    specialEvolutions: [
      {
        evolutionId: 'cactus_desert_rose',
        trigger: { type: 'neighbor_count', min: 3 },
        hint: 'Roses need company...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 4 - Cacti
  {
    id: 'cactus_water_store',
    name: 'Water Store',
    emoji: '💧',
    seedId: 'cactus',
    tier: 4,
    growthTime: 110000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'cactus_barrel',
    defaultEvolution: 'cactus_oasis',
    description: 'Returns extra water on harvest!',
    rarity: 'rare',
  },
  
  {
    id: 'cactus_ancient_barrel',
    name: 'Ancient Barrel',
    emoji: '🏺',
    seedId: 'cactus',
    tier: 4,
    growthTime: 120000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'cactus_barrel',
    defaultEvolution: 'cactus_artifact',
    rarity: 'epic',
  },
  
  {
    id: 'cactus_saguaro',
    name: 'Saguaro',
    emoji: '🌵',
    seedId: 'cactus',
    tier: 4,
    growthTime: 130000,
    visualScale: 1.8,
    pointValue: 0,
    evolvesFrom: 'cactus_tall',
    defaultEvolution: 'cactus_desert_king',
    specialEvolutions: [
      {
        evolutionId: 'cactus_eagle_perch',
        trigger: { type: 'visitor_touch', visitor: 'bluebird' },
        hint: 'Birds of a feather...',
      },
    ],
    rarity: 'rare',
  },
  
  {
    id: 'cactus_organ_pipe',
    name: 'Organ Pipe',
    emoji: '🎵',
    seedId: 'cactus',
    tier: 4,
    growthTime: 110000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'cactus_tall',
    defaultEvolution: 'cactus_music',
    rarity: 'rare',
  },
  
  // Tier 4 - Succulents
  {
    id: 'cactus_gem_plant',
    name: 'Gem Plant',
    emoji: '�',
    seedId: 'cactus',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'cactus_jade',
    defaultEvolution: 'cactus_crystal',
    rarity: 'rare',
  },
  
  {
    id: 'cactus_money_tree',
    name: 'Money Tree',
    emoji: '💰',
    seedId: 'cactus',
    tier: 4,
    growthTime: 120000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'cactus_jade',
    defaultEvolution: 'cactus_fortune',
    rarity: 'epic',
  },
  
  {
    id: 'cactus_echeveria',
    name: 'Echeveria',
    emoji: '�️',
    seedId: 'cactus',
    tier: 4,
    growthTime: 95000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'cactus_rosette',
    defaultEvolution: 'cactus_queen',
    rarity: 'uncommon',
  },
  
  {
    id: 'cactus_desert_rose',
    name: 'Desert Rose',
    emoji: '🌹',
    seedId: 'cactus',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'cactus_rosette',
    defaultEvolution: 'cactus_rose_queen',
    rarity: 'rare',
  },
  
  // Tier 4 - Special: Lithops/Living Stones
  {
    id: 'cactus_lithops',
    name: 'Living Stone',
    emoji: '🪨',
    seedId: 'cactus',
    tier: 4,
    growthTime: 150000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'cactus_succulent',
    defaultEvolution: 'cactus_ancient_stone',
    specialEvolutions: [
      {
        evolutionId: 'cactus_crystal_cactus',
        trigger: { type: 'neighbor_diverse', min: 5 },
        hint: 'Diversity creates crystals...',
      },
    ],
    rarity: 'epic',
  },
  
  // Tier 5 - MAX
  {
    id: 'cactus_oasis',
    name: 'Oasis',
    emoji: '🏝️',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 10,
    evolvesFrom: 'cactus_water_store',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'A desert miracle. Returns +5 water on harvest!',
  },
  
  {
    id: 'cactus_artifact',
    name: 'Desert Artifact',
    emoji: '🏺',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 18,
    evolvesFrom: 'cactus_ancient_barrel',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Ancient desert treasure.',
  },
  
  {
    id: 'cactus_desert_king',
    name: 'Desert King',
    emoji: '🦁',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 12,
    evolvesFrom: 'cactus_saguaro',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Ruler of the arid lands.',
  },
  
  {
    id: 'cactus_eagle_perch',
    name: 'Eagle Perch',
    emoji: '🦅',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 15,
    evolvesFrom: 'cactus_saguaro',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Where eagles dare to rest.',
  },
  
  {
    id: 'cactus_music',
    name: 'Music Cactus',
    emoji: '🎶',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 11,
    evolvesFrom: 'cactus_organ_pipe',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Plays desert melodies.',
  },
  
  {
    id: 'cactus_crystal',
    name: 'Crystal Succulent',
    emoji: '🧊',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 14,
    evolvesFrom: 'cactus_gem_plant',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Pure crystallized life.',
  },
  
  {
    id: 'cactus_fortune',
    name: 'Fortune Plant',
    emoji: '💰',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.9,
    pointValue: 20,
    evolvesFrom: 'cactus_money_tree',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Attracts wealth and prosperity.',
  },
  
  {
    id: 'cactus_queen',
    name: 'Succulent Queen',
    emoji: '👸',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 11,
    evolvesFrom: 'cactus_echeveria',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'Royalty of the succulent world.',
  },
  
  {
    id: 'cactus_rose_queen',
    name: 'Rose Queen',
    emoji: '🌹',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 12,
    evolvesFrom: 'cactus_desert_rose',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Beauty blooms in harsh lands.',
  },
  
  {
    id: 'cactus_ancient_stone',
    name: 'Ancient Stone',
    emoji: '🗿',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 18,
    evolvesFrom: 'cactus_lithops',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Older than memory.',
  },
  
  {
    id: 'cactus_crystal_cactus',
    name: 'Prism Plant',
    emoji: '💠',
    seedId: 'cactus',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 19,
    evolvesFrom: 'cactus_lithops',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'cactus_stardust',
        trigger: { type: 'golden' },
        hint: 'Golden prisms catch starlight...',
      },
    ],
    rarity: 'epic',
    description: 'Refracts light into rainbows.',
  },
  
  // Tier 6 - LEGENDARY
  {
    id: 'cactus_stardust',
    name: 'Stardust',
    emoji: '💫',
    seedId: 'cactus',
    tier: 6,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 38,
    evolvesFrom: 'cactus_crystal_cactus',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Made of actual stardust.',
  },
];
