import { Evolution } from './types';

// ===== 🍄 SPORE TREE (Fungi & Shade) =====

export const SPORE_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'spore_seed',
    name: 'Spore',
    emoji: '🍄',
    seedId: 'spore',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'spore_fungus',
    rarity: 'common',
  },
  
  // Tier 1
  {
    id: 'spore_fungus',
    name: 'Fungus',
    emoji: '🦠',
    seedId: 'spore',
    tier: 1,
    growthTime: 40000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'spore_seed',
    defaultEvolution: 'spore_mushroom',
    specialEvolutions: [
      {
        evolutionId: 'spore_dark',
        trigger: { type: 'night_water', count: 2 },
        hint: 'Darkness awakens...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: Mushrooms
  {
    id: 'spore_mushroom',
    name: 'Mushroom',
    emoji: '🍄',
    seedId: 'spore',
    tier: 2,
    growthTime: 55000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'spore_fungus',
    defaultEvolution: 'spore_portobello',
    specialEvolutions: [
      {
        evolutionId: 'spore_toadstool',
        trigger: { type: 'random', chance: 0.3 },
        hint: 'Sometimes mushrooms are... different.',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Dark/Shadow
  {
    id: 'spore_dark',
    name: 'Shadow Spore',
    emoji: '🌑',
    seedId: 'spore',
    tier: 2,
    growthTime: 60000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'spore_fungus',
    defaultEvolution: 'spore_night_bloom',
    specialEvolutions: [
      {
        evolutionId: 'spore_eerie',
        trigger: { type: 'month', month: 10 },
        hint: 'October nights...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Mushrooms
  {
    id: 'spore_portobello',
    name: 'Portobello',
    emoji: '🟤',
    seedId: 'spore',
    tier: 3,
    growthTime: 65000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'spore_mushroom',
    defaultEvolution: 'spore_gourmet',
    specialEvolutions: [
      {
        evolutionId: 'spore_pizza',
        trigger: { type: 'combo_water', count: 3 },
        hint: 'Hot and fast...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'spore_toadstool',
    name: 'Toadstool',
    emoji: '🔴',
    seedId: 'spore',
    tier: 3,
    growthTime: 70000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'spore_mushroom',
    defaultEvolution: 'spore_death_cap',
    specialEvolutions: [
      {
        evolutionId: 'spore_fairy_ring',
        trigger: { type: 'neighbor_same', min: 3 },
        hint: 'Mushrooms gather in circles...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Dark
  {
    id: 'spore_night_bloom',
    name: 'Night Bloom',
    emoji: '🌙',
    seedId: 'spore',
    tier: 3,
    growthTime: 65000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'spore_dark',
    defaultEvolution: 'spore_bat_flower',
    specialEvolutions: [
      {
        evolutionId: 'spore_eye_flower',
        trigger: { type: 'neighbor_diverse', min: 4 },
        hint: 'Sees all around it...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'spore_eerie',
    name: 'Eerie Bloom',
    emoji: '👻',
    seedId: 'spore',
    tier: 3,
    growthTime: 75000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'spore_dark',
    defaultEvolution: 'spore_skull',
    specialEvolutions: [
      {
        evolutionId: 'spore_web',
        trigger: { type: 'neighbor_count', min: 6 },
        hint: 'Webs need corners...',
      },
    ],
    rarity: 'rare',
  },
  
  // Tier 4 - Mushrooms
  {
    id: 'spore_gourmet',
    name: 'Gourmet Mushroom',
    emoji: '🟡',
    seedId: 'spore',
    tier: 4,
    growthTime: 80000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'spore_portobello',
    defaultEvolution: 'spore_chanterelle',
    specialEvolutions: [
      {
        evolutionId: 'spore_truffle',
        trigger: { type: 'golden' },
        hint: 'Rarest of the rare...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'spore_pizza',
    name: 'Pizza Mushroom',
    emoji: '🍕',
    seedId: 'spore',
    tier: 4,
    growthTime: 70000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'spore_portobello',
    defaultEvolution: 'spore_supreme',
    rarity: 'rare',
  },
  
  {
    id: 'spore_death_cap',
    name: 'Death Cap',
    emoji: '☠️',
    seedId: 'spore',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'spore_toadstool',
    defaultEvolution: 'spore_toxic',
    specialEvolutions: [
      {
        evolutionId: 'spore_wizard',
        trigger: { type: 'farmer_boosted', count: 15 },
        hint: 'The farmer knows alchemy...',
      },
    ],
    rarity: 'rare',
  },
  
  {
    id: 'spore_fairy_ring',
    name: 'Fairy Ring',
    emoji: '🧚',
    seedId: 'spore',
    tier: 4,
    growthTime: 95000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'spore_toadstool',
    defaultEvolution: 'spore_fairy_kingdom',
    rarity: 'epic',
  },
  
  // Tier 4 - Dark
  {
    id: 'spore_bat_flower',
    name: 'Bat Flower',
    emoji: '🦇',
    seedId: 'spore',
    tier: 4,
    growthTime: 85000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'spore_night_bloom',
    defaultEvolution: 'spore_vampire_bloom',
    rarity: 'rare',
  },
  
  {
    id: 'spore_eye_flower',
    name: 'Eye Flower',
    emoji: '👁️',
    seedId: 'spore',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'spore_night_bloom',
    defaultEvolution: 'spore_all_seeing',
    rarity: 'epic',
  },
  
  {
    id: 'spore_skull',
    name: 'Skull Bloom',
    emoji: '💀',
    seedId: 'spore',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'spore_eerie',
    defaultEvolution: 'spore_ghost_orchid',
    rarity: 'epic',
  },
  
  {
    id: 'spore_web',
    name: 'Web Flower',
    emoji: '🕸️',
    seedId: 'spore',
    tier: 4,
    growthTime: 95000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'spore_eerie',
    defaultEvolution: 'spore_spider_lily',
    rarity: 'epic',
  },
  
  // Tier 5 - MAX Mushrooms
  {
    id: 'spore_chanterelle',
    name: 'Chanterelle',
    emoji: '🟡',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 9,
    evolvesFrom: 'spore_gourmet',
    defaultEvolution: null,
    rarity: 'uncommon',
    description: 'Prized by chefs worldwide.',
  },
  
  {
    id: 'spore_truffle',
    name: 'Diamond Truffle',
    emoji: '💎',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 25,
    evolvesFrom: 'spore_gourmet',
    defaultEvolution: null,
    rarity: 'legendary',
    description: 'Worth its weight in gold.',
  },
  
  {
    id: 'spore_supreme',
    name: 'Supreme Shroom',
    emoji: '🍕',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 11,
    evolvesFrom: 'spore_pizza',
    defaultEvolution: null,
    rarity: 'rare',
    description: 'All the toppings.',
  },
  
  {
    id: 'spore_toxic',
    name: 'Toxic Terror',
    emoji: '☢️',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 12,
    evolvesFrom: 'spore_death_cap',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Handle with care (not really toxic).',
  },
  
  {
    id: 'spore_wizard',
    name: 'Wizard Cap',
    emoji: '🧙',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 18,
    evolvesFrom: 'spore_death_cap',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Grants +10 INT (not really).',
  },
  
  {
    id: 'spore_fairy_kingdom',
    name: 'Fairy Kingdom',
    emoji: '🧚',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 20,
    evolvesFrom: 'spore_fairy_ring',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'A tiny civilization.',
  },
  
  // Tier 5 - MAX Dark
  {
    id: 'spore_vampire_bloom',
    name: 'Vampire Bloom',
    emoji: '🧛',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 14,
    evolvesFrom: 'spore_bat_flower',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Blooms only at night.',
  },
  
  {
    id: 'spore_all_seeing',
    name: 'All-Seeing Flower',
    emoji: '🔮',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 18,
    evolvesFrom: 'spore_eye_flower',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Knows your deepest secrets.',
  },
  
  {
    id: 'spore_ghost_orchid',
    name: 'Ghost Orchid',
    emoji: '👻',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 19,
    evolvesFrom: 'spore_skull',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Hauntingly beautiful.',
  },
  
  {
    id: 'spore_spider_lily',
    name: 'Spider Lily',
    emoji: '🕷️',
    seedId: 'spore',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 16,
    evolvesFrom: 'spore_web',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'spore_black_widow',
        trigger: { type: 'golden' },
        hint: 'Golden darkness...',
      },
    ],
    rarity: 'epic',
    description: 'Eight-legged elegance.',
  },
  
  // Tier 6 - LEGENDARY
  {
    id: 'spore_black_widow',
    name: 'Black Widow',
    emoji: '🖤',
    seedId: 'spore',
    tier: 6,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 30,
    evolvesFrom: 'spore_spider_lily',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Beautiful and deadly (looking).',
  },
];
