import { Evolution } from './types';

// ===== 🌱 SPROUT TREE (Flowers & Herbs) =====

export const SPROUT_EVOLUTIONS: Evolution[] = [
  // Tier 0 - Seed
  {
    id: 'sprout_seed',
    name: 'Sprout',
    emoji: '🌱',
    seedId: 'sprout',
    tier: 0,
    growthTime: 0,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: null,
    defaultEvolution: 'sprout_seedling',
    rarity: 'common',
  },
  
  // Tier 1 - Seedling
  {
    id: 'sprout_seedling',
    name: 'Seedling',
    emoji: '🌿',
    seedId: 'sprout',
    tier: 1,
    growthTime: 30000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'sprout_seed',
    defaultEvolution: 'sprout_bud',
    specialEvolutions: [
      {
        evolutionId: 'sprout_herb',
        trigger: { type: 'combo_water', count: 2 },
        hint: 'Try combo watering...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch A: Flowers
  {
    id: 'sprout_bud',
    name: 'Bud',
    emoji: '🌼',
    seedId: 'sprout',
    tier: 2,
    growthTime: 45000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'sprout_seedling',
    defaultEvolution: 'sprout_tulip',
    specialEvolutions: [
      {
        evolutionId: 'sprout_sunflower',
        trigger: { type: 'neighbor_count', min: 4 },
        hint: 'Surround with friends...',
      },
    ],
    rarity: 'common',
  },
  
  // Tier 2 - Branch B: Herbs
  {
    id: 'sprout_herb',
    name: 'Herb',
    emoji: '🍃',
    seedId: 'sprout',
    tier: 2,
    growthTime: 40000,
    visualScale: 1.0,
    pointValue: 0,
    evolvesFrom: 'sprout_seedling',
    defaultEvolution: 'sprout_mint',
    specialEvolutions: [
      {
        evolutionId: 'sprout_tea',
        trigger: { type: 'farmer_boosted', count: 10 },
        hint: 'The farmer knows best...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Flowers
  {
    id: 'sprout_tulip',
    name: 'Tulip',
    emoji: '🌷',
    seedId: 'sprout',
    tier: 3,
    growthTime: 60000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'sprout_bud',
    defaultEvolution: 'sprout_blossom',
    specialEvolutions: [
      {
        evolutionId: 'sprout_rose',
        trigger: { type: 'golden' },
        hint: 'Only the golden ones...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'sprout_sunflower',
    name: 'Sunflower',
    emoji: '🌻',
    seedId: 'sprout',
    tier: 3,
    growthTime: 60000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'sprout_bud',
    defaultEvolution: 'sprout_sun_spirit',
    specialEvolutions: [
      {
        evolutionId: 'sprout_solar_bloom',
        trigger: { type: 'visitor_touch', visitor: 'butterfly' },
        hint: 'Butterflies love sunflowers...',
      },
    ],
    rarity: 'uncommon',
  },
  
  // Tier 3 - Herbs
  {
    id: 'sprout_mint',
    name: 'Mint',
    emoji: '🌿',
    seedId: 'sprout',
    tier: 3,
    growthTime: 55000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'sprout_herb',
    defaultEvolution: 'sprout_frost_mint',
    specialEvolutions: [
      {
        evolutionId: 'sprout_frost_mint',
        trigger: { type: 'night_water', count: 3 },
        hint: 'Cool night waters...',
      },
    ],
    rarity: 'uncommon',
  },
  
  {
    id: 'sprout_tea',
    name: 'Tea Leaf',
    emoji: '🫖',
    seedId: 'sprout',
    tier: 3,
    growthTime: 50000,
    visualScale: 1.1,
    pointValue: 0,
    evolvesFrom: 'sprout_herb',
    defaultEvolution: 'sprout_golden_tea',
    rarity: 'uncommon',
  },
  
  // Tier 4 - Flowers
  {
    id: 'sprout_blossom',
    name: 'Blossom',
    emoji: '🌸',
    seedId: 'sprout',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.4,
    pointValue: 0,
    evolvesFrom: 'sprout_tulip',
    defaultEvolution: 'sprout_bouquet',
    specialEvolutions: [
      {
        evolutionId: 'sprout_sakura',
        trigger: { type: 'season', season: 'spring' },
        hint: 'Blooms best in spring...',
      },
      {
        evolutionId: 'sprout_lavender',
        trigger: { type: 'night_water', count: 3 },
        hint: 'Prefers twilight care...',
      },
    ],
    rarity: 'common',
  },
  
  {
    id: 'sprout_rose',
    name: 'Rose',
    emoji: '🌹',
    seedId: 'sprout',
    tier: 4,
    growthTime: 90000,
    visualScale: 1.3,
    pointValue: 0,
    evolvesFrom: 'sprout_tulip',
    defaultEvolution: 'sprout_red_rose',
    specialEvolutions: [
      {
        evolutionId: 'sprout_black_rose',
        trigger: { type: 'night_water', count: 5 },
        hint: 'Embrace the darkness...',
      },
    ],
    rarity: 'rare',
  },
  
  {
    id: 'sprout_sun_spirit',
    name: 'Sun Spirit',
    emoji: '🌞',
    seedId: 'sprout',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.6,
    pointValue: 0,
    evolvesFrom: 'sprout_sunflower',
    defaultEvolution: 'sprout_solar_king',
    rarity: 'rare',
  },
  
  {
    id: 'sprout_solar_bloom',
    name: 'Solar Bloom',
    emoji: '🔆',
    seedId: 'sprout',
    tier: 4,
    growthTime: 100000,
    visualScale: 1.5,
    pointValue: 0,
    evolvesFrom: 'sprout_sunflower',
    defaultEvolution: 'sprout_radiant',
    rarity: 'rare',
  },
  
  // Tier 4 - Herbs  
  {
    id: 'sprout_frost_mint',
    name: 'Frost Mint',
    emoji: '❄️',
    seedId: 'sprout',
    tier: 4,
    growthTime: 80000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'sprout_mint',
    defaultEvolution: 'sprout_ice_crystal',
    rarity: 'rare',
  },
  
  {
    id: 'sprout_golden_tea',
    name: 'Golden Tea',
    emoji: '🍵',
    seedId: 'sprout',
    tier: 4,
    growthTime: 75000,
    visualScale: 1.2,
    pointValue: 0,
    evolvesFrom: 'sprout_tea',
    defaultEvolution: 'sprout_zen_garden',
    specialEvolutions: [
      {
        evolutionId: 'sprout_zen_garden',
        trigger: { type: 'farmer_boosted', count: 20 },
        hint: 'Zen requires patience...',
      },
    ],
    rarity: 'rare',
  },
  
  // Tier 5 - MAX Flowers (Harvestable!)
  {
    id: 'sprout_bouquet',
    name: 'Bouquet',
    emoji: '💐',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 5,
    evolvesFrom: 'sprout_blossom',
    defaultEvolution: null,
    rarity: 'common',
    description: 'A beautiful arrangement of flowers.',
  },
  
  {
    id: 'sprout_sakura',
    name: 'Sakura',
    emoji: '🎀',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 8,
    evolvesFrom: 'sprout_blossom',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'sprout_imperial_sakura',
        trigger: { type: 'golden' },
        hint: 'A golden sakura is truly imperial...',
      },
    ],
    rarity: 'rare',
    description: 'Delicate spring blossoms.',
  },
  
  {
    id: 'sprout_lavender',
    name: 'Lavender',
    emoji: '💜',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 6,
    evolvesFrom: 'sprout_blossom',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'sprout_mystic_lavender',
        trigger: { type: 'night_water', count: 5 },
        hint: 'Mystical under moonlight...',
      },
    ],
    rarity: 'uncommon',
    description: 'Calming purple blooms.',
  },
  
  {
    id: 'sprout_red_rose',
    name: 'Red Rose',
    emoji: '🌹',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.7,
    pointValue: 8,
    evolvesFrom: 'sprout_rose',
    defaultEvolution: null,
    specialEvolutions: [
      {
        evolutionId: 'sprout_crystal_rose',
        trigger: { type: 'golden' },
        hint: 'Crystalline beauty...',
      },
    ],
    rarity: 'rare',
    description: 'The classic symbol of love.',
  },
  
  {
    id: 'sprout_black_rose',
    name: 'Black Rose',
    emoji: '🖤',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 5,
    evolvesFrom: 'sprout_rose',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Rare and mysterious.',
  },
  
  {
    id: 'sprout_solar_king',
    name: 'Solar King',
    emoji: '👑',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 5,
    evolvesFrom: 'sprout_sun_spirit',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Ruler of the sunflowers.',
  },
  
  {
    id: 'sprout_radiant',
    name: 'Radiant Bloom',
    emoji: '✨',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.8,
    pointValue: 9,
    evolvesFrom: 'sprout_solar_bloom',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Glows with inner light.',
  },
  
  // Tier 5 - MAX Herbs
  {
    id: 'sprout_ice_crystal',
    name: 'Ice Crystal Herb',
    emoji: '🧊',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.5,
    pointValue: 9,
    evolvesFrom: 'sprout_frost_mint',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Frozen botanical perfection.',
  },
  
  {
    id: 'sprout_zen_garden',
    name: 'Zen Garden',
    emoji: '🧘',
    seedId: 'sprout',
    tier: 5,
    growthTime: 0,
    visualScale: 1.6,
    pointValue: 6,
    evolvesFrom: 'sprout_golden_tea',
    defaultEvolution: null,
    rarity: 'epic',
    description: 'Inner peace manifest.',
  },
  
  // Tier 6 - LEGENDARY
  {
    id: 'sprout_imperial_sakura',
    name: 'Imperial Sakura',
    emoji: '🏯',
    seedId: 'sprout',
    tier: 6,
    growthTime: 0,
    visualScale: 2.2,
    pointValue: 12,
    evolvesFrom: 'sprout_sakura',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Fit for an emperor.',
  },
  
  {
    id: 'sprout_mystic_lavender',
    name: 'Mystic Lavender',
    emoji: '🔮',
    seedId: 'sprout',
    tier: 6,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 10,
    evolvesFrom: 'sprout_lavender',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Whispers of ancient magic.',
  },
  
  {
    id: 'sprout_crystal_rose',
    name: 'Crystal Rose',
    emoji: '💎',
    seedId: 'sprout',
    tier: 6,
    growthTime: 0,
    visualScale: 2.0,
    pointValue: 12,
    evolvesFrom: 'sprout_red_rose',
    defaultEvolution: null,
    isLegendary: true,
    rarity: 'legendary',
    description: 'Pure crystallized beauty.',
  },
];
